
clear all
addpath(genpath('/gs/project/gsf-624-aa/quarantaine/niak-boss-0.13.4/'))

addpath(genpath('/gs/project/gsf-624-aa/quarantaine/niak_dev_git/extensions/surfstab/'))


in_path = '/gs/project/gsf-624-aa/database2/adni2/fmri_preprocess/fmri/';
part_path = '/gs/project/gsf-624-aa/database2/preventad/templates/template_cambridge_basc_multiscale_sym_scale012.mnc.gz';
out_path = '/gs/project/gsf-624-aa/database2/preventad/results/adni_scores_s012_20160121/'; % s12 s20 s36
file_template = 'fmri_subject[0-9]*_session1_r1d[0-9]*.mnc.gz';
files_include = {'session1'};

files_reject = {'subject4213',... % <70 vols après scrubbing
'subject4171',...
'subject5059',...
'subject4485',...
'subject5242',...
'subject5178',...
'subject4679',...
'subject4005',...
'subject4225',...
'subject4477',...
'subject1268',...
'subject4661',...
'subject4884',...
'subject4449',...
'subject5091',...
'subject4557',...
'subject4546',...
'subject4468',...
'subject4496',...
'subject5208',...
'subject4883',...
'subject1186',...
'subject2043',...
'subject2138',...
'subject2396',...
'subject4219',...
'subject4269',...
'subject4408',...
'subject4433',...
'subject4442',...
'subject4579',...
'subject4589',...
'subject4605',...
'subject4768',...
'subject4809',...
'subject5019',...
'subject5148',...
'subject5153',...
'subject5180',...
'subject4021',... % problèmes coregistrations
'subject4511',...
'subject4661',...
'subject0107'};


% Search for the files we need and build the structure
f = dir(in_path);
[~, path_name, ~] = niak_fileparts(in_path);
in_strings = {f.name};
in_strings = in_strings(3:end);
in_files.fmri = struct;

%
for f_id = 1:numel(in_strings)
    in_string = in_strings{f_id};
    tmp_path = [in_path filesep in_string];
    [start, stop] = regexp(in_string, file_template);
    if ~isempty(start) && ~isempty(stop)
        [~, fname, ~] = niak_fileparts(in_string(start:stop));
        % See if it is in the exclusion list
        get_it = 1;
        for rej_id = 1:length(files_reject)
            rej_name = files_reject{rej_id};
            if findstr(rej_name,fname)
                get_it = 0;
            else
            end
        end
        if get_it == 1
            sub_name = [path_name '_' fname];
            in_files.fmri.(fname) = [in_path filesep in_string];
            a = [in_path filesep in_string];
        else
            fprintf('We do not like subject %s\n',fname);
        end
    end
end
    


in_files.part = part_path;
opt.folder_out = out_path;
% Compute the number of matched files
fnames = fieldnames(in_files.fmri);
numf = length(fnames);
disp(sprintf('I found %d files in %s.\n', numf, in_path));
opt.psom.max_queued = 300;
opt.scores.flag_target = true;
opt.scores.flag_deal = true;
disp('Running the pipeline now.')
pipeline = niak_pipeline_stability_scores(in_files, opt);
